CONTIKI_PROJECT = test
all: $(CONTIKI_PROJECT)

#MODULES += os/services/shell
# CONTIKI_TARGET_SOURCEFILES += si7021.c tsl2561.c
MAKE_MAC = MAKE_MAC_TSCH
# MODULES += arch/platform/cc2538dk/dev
MODULES += os/services/rpl-border-router

#MAKE_MAC = MAKE_MAC_TSCH
#MODULES += os/services/rpl-border-router

CONTIKI = ../..
include $(CONTIKI)/Makefile.include