CONTIKI_PROJECT = test
all: $(CONTIKI_PROJECT)

MODULES += os/services/simple-energest

# MAKE_MAC = MAKE_MAC_TSCH

# MODULES += os/services/orchestra

# MODULES += os/net/mac/tsch/sixtop

# CFLAGS += -DWITH_SECURITY=1

# CFLAGS += -DWITH_PERIODIC_ROUTES_PRINT=1

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
